package homework2510;

public class Main {
    public static void main(String[] args) {
        Mammal animalFirst = new Mammal("Млекопитающие", "Встречаются в каждой среде обитания", "Теплокровные", "Волосяной покров", "Позвоночные", "Всеядные");
        animalFirst.printing("Млекопитающие", "Встречаются в каждой среде обитания", "Теплокровные", "Волосяной покров", "Позвоночные", "Всеядные");
        animalFirst.say();
        animalFirst.howIEating("Позвоночные");
        animalFirst.dependenceTemperature("Теплокровные");
        animalFirst.eatIam("Всеядные");
        System.out.println(" ");
        Fish animalSecond = new Fish("Рыбы", "Водная", "Холоднокровные", "Чешуя", "Позвоночные", "Зависит от вида");
        animalSecond.printing("Рыбы", "Водная", "Холоднокровные", "Чешуя", "Позвоночные", "Зависит от вида");
        animalSecond.say();
        animalSecond.howIEating("Позвоночные");
        animalSecond.dependenceTemperature("Холоднокровные");
        animalSecond.eatIam("Зависит от вида");
        System.out.println(" ");
        Arthropods animalThree = new Arthropods("Членистоногие", "Встречаются в каждой среде обитания", "Холоднокровные", "Членистое тело", "Беспозвоночные", "Травоядные");
        animalThree.printing("Членистоногие", "Встречаются в каждой среде обитания", "Холоднокровные", "Членистое тело", "Беспозвоночные", "Травоядные");
        animalThree.say();
        animalThree.howIEating("Беспозвоночные");
        animalThree.dependenceTemperature("Холоднокровные");
        animalThree.eatIam("Травоядные");
        System.out.println(" ");
        Reptiles animalForth = new Reptiles("Пресмыкающиеся", "Наземная", "Холоднокровные", "Сухая кожа с чешуями", "Позвоночные", "Хищники");
        animalForth.printing("Пресмыкающиеся", "Наземная", "Холоднокровные", "Сухая кожа с чешуями", "Позвоночные", "Хищники");
        animalForth.say();
        animalForth.howIEating("Позвоночные");
        animalForth.dependenceTemperature("Холоднокровные");
        animalForth.eatIam("Хищники");
        System.out.println(" ");
        Worms animalFive = new Worms("Черви", "Почвенная", "Холоднокровные", "Тело без скелета", "Беспозвоночные", "Хищники");
        animalFive.printing("Черви", "Почвенная", "Холоднокровные", "Тело без скелета", "Беспозвоночные", "Хищники");
        animalFive.say();
        animalFive.howIEating("Беспозвоночные");
        animalFive.dependenceTemperature("Холоднокровные");
        animalFive.eatIam("Хищники");
        System.out.println(" ");
        Echinoderms animalSix = new Echinoderms("Иглокожие", "Водная", "Холоднокровные", "Известковый скелет с иглами", "Беспозвоночные", "Хищники");
        animalSix.printing("Иглокожие", "Водная", "Холоднокровные", "Известковый скелет с иглами", "Беспозвоночные", "Хищники");
        animalSix.say();
        animalSix.howIEating("Беспозвоночные");
        animalSix.dependenceTemperature("Холоднокровные");
        animalSix.eatIam("Хищники");
        System.out.println(" ");
        Crustaceans animalSeven = new Crustaceans("Ракообразные", "Водная", "Холоднокровные", "Хитиновый панцирь", "Беспозвоночные", "Хищники");
        animalSeven.printing("Ракообразные", "Водная", "Холоднокровные", "Хитиновый панцирь", "Беспозвоночные", "Хищники");
        animalSeven.say();
        animalSeven.howIEating("Беспозвоночные");
        animalSeven.dependenceTemperature("Холоднокровные");
        animalSeven.eatIam("Хищники");
        System.out.println(" ");
        Chordates animalEight = new Chordates("Хордовые", "Встречаются в каждой среде обитания", "Холоднокровные", "Жаберные щели", "Беспозвоночные", "Зависит от вида");
        animalEight.printing("Хордовые", "Встречаются в каждой среде обитания", "Холоднокровные", "Жаберные щели", "Беспозвоночные", "Зависит от вида");
        animalEight.say();
        animalEight.howIEating("Беспозвоночные");
        animalEight.dependenceTemperature("Холоднокровные");
        animalEight.eatIam("Зависит от вида");
        System.out.println(" ");
        Birds animalNine = new Birds("Птицы", "Наземно-воздушная", "Теплокровные", "Перья, крылья", "Позвоночные", "Зависит от вида");
        animalNine.printing("Птицы", "Наземно-воздушная", "Теплокровные", "Перья, крылья", "Позвоночные", "Зависит от вида");
        animalNine.say();
        animalNine.howIEating("Позвоночные");
        animalNine.dependenceTemperature("Теплокровные");
        animalNine.eatIam("Зависит от вида");
        System.out.println(" ");
        Amphibians animalTen = new Amphibians("Земноводные", "Водная, приближенные к воде", "Холоднокровные", "Голая кожа без чешуи", "Позвоночные", "Хищники");
        animalTen.printing("Земноводные", "Водная, приближенные к воде", "Холоднокровные", "Голая кожа без чешуи", "Позвоночные", "Хищники");
        animalTen.say();
        animalTen.howIEating("Позвоночные");
        animalTen.dependenceTemperature("Холоднокровные");
        animalTen.eatIam("Хищники");
    }
}